### ISSUE TITLE
`main` tag is confusing

### ISSUE THREAD

**Issue by sameo** [riscv-non-isa/riscv-ap-tee#16]
We have a `main` git tag which also happens to be the name of the default branch.

This causes confusion and git warnings/errors:

```
warning: refname 'main' is ambiguous.`
```

I propose to create a new tag on the same ref and delete the `main` tag.

**Comment by sameo** [comment]
cc @rsahita

**Comment by rsahita** [comment]
I have created an alternate tag "test" on the same ref - but I cannot delete the tag using the refs/tag/main handle - perhaps since @jjscheel created that (it shows as a verified tag and does not give me the option to delete the tag on Github either).
