### ISSUE TITLE
Need a recent PDF in this repository

### ISSUE THREAD

**Issue by dlweaver** [riscv-non-isa/riscv-ap-tee#2]
Could we arrange to leave a recent PDF of this specification in GitHub, so people who visit this GitHub site can grab a copy of the document to read/review?  Not everyone has the know-how, time, or tools installed to download the whole project and build it, when all they want to do is read a PDF of the spec.   THanks!

**Comment by rsahita** [comment]
PDF of the spec added (in the specification dir)
