### ISSUE TITLE
CoVE-IO FID namespace

### ISSUE THREAD

**Issue by sameo** [riscv-non-isa/riscv-ap-tee#39]
The [CoVE-IO](https://github.com/riscv-non-isa/riscv-ap-tee-io) specification extends the CoVE ABI for supporting device direct assignment into TVMs.

The CoVE-IO ABI extensions require their own SBI FIDs and are currently left TBD in the [spec](https://github.com/riscv-non-isa/riscv-ap-tee-io/blob/main/specification/09-coveio_abi.adoc). I propose that we assign a specific FID range for CoVE-IO, so that the CoVE and CoVE-IO FIDs can be formally defined without overlapping or interleaving.

Since FIDs can fill an entire register (`a6`), one possibility would be to reserve the top half `COVG` and `COVH` EID spaces for CoVE extensions. CoVE-IO could e.g take 6 bits from there and use them as needed.

@rsahita @jyao1 WDYT?

**Comment by jyao1** [comment]
Yes, I like this proposal to separate role and responsibility.

**Comment by rsahita** [comment]
sounds good - we should also make sure there are some reserved portions for other future extensions.

**Comment by sameo** [comment]
> sounds good - we should also make sure there are some reserved portions for other future extensions.

Yep.
I'll send a PR for this.
