### ISSUE TITLE
[Qualcomm feedback] Chapter 4: Section 4.2 Clarify TSM must be in confidential memory

### ISSUE THREAD

**Issue by rsahita** [riscv-non-isa/riscv-ap-tee#49]
Reference: [link](https://lists.riscv.org/g/tech-ap-tee/message/128)

> T1: Loss of confidentiality of TVMs and TSM **memory** via in-scope adversaries that may read
TSM/TVM memory via CPU accesses

replace memory with private memory?
There is no definition of "private" memory, I don't believe TSM can use any memory which is not "private". Only TVMs can have both shared and confidential memory.

**Comment by rsahita** [comment]
changed this to say:

> T1: Loss of confidentiality of TVMs and TSM confidential memory via in-scope
> adversaries that may read TSM/TVM confidential memory via CPU

**Comment by rsahita** [comment]
address in PR #71 

cc @ozkoyuncu

**Comment by ozkoyuncu** [comment]
Agreed,  could not find reference to private memory in the doc either. the comment is a bit confusing as what it is suggesting. I think it is ok
