### ISSUE TITLE
[Qualcomm feedback] Chapter 9.11 onwards (fix ABI errors)

### ISSUE THREAD

**Issue by rsahita** [riscv-non-isa/riscv-ap-tee#65]
Reference: [link](https://lists.riscv.org/g/tech-ap-tee/message/128)

> sbi_covh_add_tvm_page_table_pages

tsm_page_type is not passed as parameter. Missing?

> Copies num_pages pages from non-confidential memory

fix num_pages markup style in 9.11 9.13 and 9.14

> sbi_covh_add_tvm_measured_pages

tvm_guest_gpa missing as potentially invalid address.

> sbi_covh_create_tvm_vcpu

Error code missing for cases where input requirements are not met by tvm_stage_page_addr param.

> 9.16 "0" 

should be SBI_SUCCESS (fix error code in table to SBI_SUCCESS)

**Comment by rsahita** [comment]
Fixed in #66 @osman-koyuncu-qualcomm @atishp04

**Comment by ozkoyuncu** [comment]
@rsahita  ack. for some reason I don't get the tag notification

**Comment by eckhard-delfs-qualcomm** [comment]
@ozkoyuncu : Testing github notification / Please ignore.

**Comment by rsahita** [comment]
addressed in #66
